name: Build

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
env:
  IMAGE_NAME: rust-llvm
  IMAGE_VERSION: 14-1.67

jobs:
  test-windows:
    name: Test Windows
    runs-on: windows-2022
    env:
      toolchain-version: 1.67.0
      llvm-version: 15.0.7
    steps:

      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.toolchain-version }}

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.llvm-version }}
          directory: "./llvm"

      - name: Release Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
 
      - uses: actions/upload-artifact@master
        with:
          name: eris.exe
          path: target/release/eris-lang.exe
